# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mines.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(191, 257)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(6, 2, 6, 2)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelMines = QtWidgets.QLabel(self.frame)
        self.labelMines.setMinimumSize(QtCore.QSize(50, 0))
        self.labelMines.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMines.setObjectName("labelMines")
        self.horizontalLayout_2.addWidget(self.labelMines)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.smileButton = QtWidgets.QPushButton(self.frame)
        self.smileButton.setMinimumSize(QtCore.QSize(35, 35))
        self.smileButton.setMaximumSize(QtCore.QSize(35, 35))
        self.smileButton.setText("")
        self.smileButton.setObjectName("smileButton")
        self.horizontalLayout_2.addWidget(self.smileButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.labelTime = QtWidgets.QLabel(self.frame)
        self.labelTime.setMinimumSize(QtCore.QSize(50, 0))
        self.labelTime.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTime.setObjectName("labelTime")
        self.horizontalLayout_2.addWidget(self.labelTime)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidget.setObjectName("stackedWidget")
        self.newGamePage = QtWidgets.QWidget()
        self.newGamePage.setObjectName("newGamePage")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.newGamePage)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 4, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 4, 0, 1, 1)
        self.pushButton_9x9 = QtWidgets.QPushButton(self.newGamePage)
        self.pushButton_9x9.setObjectName("pushButton_9x9")
        self.gridLayout_4.addWidget(self.pushButton_9x9, 1, 1, 1, 1)
        self.pushButton_16x30 = QtWidgets.QPushButton(self.newGamePage)
        self.pushButton_16x30.setObjectName("pushButton_16x30")
        self.gridLayout_4.addWidget(self.pushButton_16x30, 3, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem4, 5, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem5, 0, 1, 1, 1)
        self.pushButton_16x16 = QtWidgets.QPushButton(self.newGamePage)
        self.pushButton_16x16.setObjectName("pushButton_16x16")
        self.gridLayout_4.addWidget(self.pushButton_16x16, 2, 1, 1, 1)
        self.levelBox = QtWidgets.QComboBox(self.newGamePage)
        self.levelBox.setObjectName("levelBox")
        self.levelBox.addItem("")
        self.levelBox.addItem("")
        self.levelBox.addItem("")
        self.levelBox.addItem("")
        self.gridLayout_4.addWidget(self.levelBox, 4, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.newGamePage)
        self.gamePage = QtWidgets.QWidget()
        self.gamePage.setObjectName("gamePage")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gamePage)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.fieldWidget = QtWidgets.QWidget(self.gamePage)
        self.fieldWidget.setObjectName("fieldWidget")
        self.gameGrid = QtWidgets.QGridLayout(self.fieldWidget)
        self.gameGrid.setContentsMargins(0, 0, 0, 0)
        self.gameGrid.setSpacing(0)
        self.gameGrid.setObjectName("gameGrid")
        self.gridLayout_6.addWidget(self.fieldWidget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.gamePage)
        self.winPage = QtWidgets.QWidget()
        self.winPage.setObjectName("winPage")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.winPage)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.stackedWidget.addWidget(self.winPage)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 191, 25))
        self.menubar.setObjectName("menubar")
        self.menuGame = QtWidgets.QMenu(self.menubar)
        self.menuGame.setObjectName("menuGame")
        MainWindow.setMenuBar(self.menubar)
        self.actionNew_game = QtWidgets.QAction(MainWindow)
        self.actionNew_game.setObjectName("actionNew_game")
        self.actionRecords = QtWidgets.QAction(MainWindow)
        self.actionRecords.setObjectName("actionRecords")
        self.actionRestart = QtWidgets.QAction(MainWindow)
        self.actionRestart.setObjectName("actionRestart")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionRules = QtWidgets.QAction(MainWindow)
        self.actionRules.setObjectName("actionRules")
        self.actionInfo = QtWidgets.QAction(MainWindow)
        self.actionInfo.setObjectName("actionInfo")
        self.actionLevel = QtWidgets.QAction(MainWindow)
        self.actionLevel.setObjectName("actionLevel")
        self.menuGame.addAction(self.actionNew_game)
        self.menuGame.addAction(self.actionRestart)
        self.menuGame.addAction(self.actionExit)
        self.menubar.addAction(self.menuGame.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelMines.setText(_translate("MainWindow", "0"))
        self.labelTime.setText(_translate("MainWindow", "0"))
        self.pushButton_9x9.setText(_translate("MainWindow", "9x9"))
        self.pushButton_16x30.setText(_translate("MainWindow", "16x30"))
        self.pushButton_16x16.setText(_translate("MainWindow", "16x16"))
        self.levelBox.setItemText(0, _translate("MainWindow", "easy"))
        self.levelBox.setItemText(1, _translate("MainWindow", "normal"))
        self.levelBox.setItemText(2, _translate("MainWindow", "hard"))
        self.levelBox.setItemText(3, _translate("MainWindow", "insane"))
        self.menuGame.setTitle(_translate("MainWindow", "Game"))
        self.actionNew_game.setText(_translate("MainWindow", "New game"))
        self.actionRecords.setText(_translate("MainWindow", "Records"))
        self.actionRestart.setText(_translate("MainWindow", "Restart game"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionRules.setText(_translate("MainWindow", "Rules"))
        self.actionInfo.setText(_translate("MainWindow", "Info"))
        self.actionLevel.setText(_translate("MainWindow", "Level"))

