# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IPA.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(730, 350)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(730, 350))
        MainWindow.setMaximumSize(QtCore.QSize(800, 450))
        MainWindow.setStyleSheet("background-color: white")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(730, 350))
        self.centralwidget.setMaximumSize(QtCore.QSize(800, 450))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 7, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 4, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 7, 1, 1, 1)
        self.vowelsLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vowelsLabel.sizePolicy().hasHeightForWidth())
        self.vowelsLabel.setSizePolicy(sizePolicy)
        self.vowelsLabel.setMouseTracking(True)
        self.vowelsLabel.setFrameShape(QtWidgets.QFrame.Panel)
        self.vowelsLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.vowelsLabel.setLineWidth(1)
        self.vowelsLabel.setMidLineWidth(0)
        self.vowelsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.vowelsLabel.setWordWrap(False)
        self.vowelsLabel.setIndent(4)
        self.vowelsLabel.setObjectName("vowelsLabel")
        self.gridLayout.addWidget(self.vowelsLabel, 0, 0, 1, 1)
        self.nearCloseLabel = QtWidgets.QLabel(self.centralwidget)
        self.nearCloseLabel.setMouseTracking(True)
        self.nearCloseLabel.setStyleSheet("background-color: rgb(78, 154, 6)")
        self.nearCloseLabel.setFrameShape(QtWidgets.QFrame.Panel)
        self.nearCloseLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.nearCloseLabel.setLineWidth(1)
        self.nearCloseLabel.setMidLineWidth(0)
        self.nearCloseLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nearCloseLabel.setWordWrap(False)
        self.nearCloseLabel.setIndent(4)
        self.nearCloseLabel.setObjectName("nearCloseLabel")
        self.gridLayout.addWidget(self.nearCloseLabel, 2, 0, 1, 1)
        self.nearFrontLabel = QtWidgets.QLabel(self.centralwidget)
        self.nearFrontLabel.setMouseTracking(True)
        self.nearFrontLabel.setStyleSheet("background-color: rgb(78, 154, 6)")
        self.nearFrontLabel.setFrameShape(QtWidgets.QFrame.Panel)
        self.nearFrontLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.nearFrontLabel.setLineWidth(1)
        self.nearFrontLabel.setMidLineWidth(0)
        self.nearFrontLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nearFrontLabel.setWordWrap(False)
        self.nearFrontLabel.setIndent(4)
        self.nearFrontLabel.setObjectName("nearFrontLabel")
        self.gridLayout.addWidget(self.nearFrontLabel, 0, 2, 1, 1)
        self.closeMidLabel = QtWidgets.QLabel(self.centralwidget)
        self.closeMidLabel.setMouseTracking(True)
        self.closeMidLabel.setStyleSheet("background-color: rgb(78, 154, 6)")
        self.closeMidLabel.setFrameShape(QtWidgets.QFrame.Panel)
        self.closeMidLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.closeMidLabel.setLineWidth(1)
        self.closeMidLabel.setMidLineWidth(0)
        self.closeMidLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.closeMidLabel.setWordWrap(False)
        self.closeMidLabel.setIndent(4)
        self.closeMidLabel.setObjectName("closeMidLabel")
        self.gridLayout.addWidget(self.closeMidLabel, 3, 0, 1, 1)
        self.nearOpenLabel = QtWidgets.QLabel(self.centralwidget)
        self.nearOpenLabel.setMouseTracking(True)
        self.nearOpenLabel.setStyleSheet("background-color: rgb(78, 154, 6)")
        self.nearOpenLabel.setFrameShape(QtWidgets.QFrame.Panel)
        self.nearOpenLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.nearOpenLabel.setLineWidth(1)
        self.nearOpenLabel.setMidLineWidth(0)
        self.nearOpenLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nearOpenLabel.setWordWrap(False)
        self.nearOpenLabel.setIndent(4)
        self.nearOpenLabel.setObjectName("nearOpenLabel")
        self.gridLayout.addWidget(self.nearOpenLabel, 6, 0, 1, 1)
        self.openLabel = QtWidgets.QLabel(self.centralwidget)
        self.openLabel.setMouseTracking(True)
        self.openLabel.setStyleSheet("background-color: rgb(78, 154, 6)")
        self.openLabel.setFrameShape(QtWidgets.QFrame.Panel)
        self.openLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.openLabel.setLineWidth(1)
        self.openLabel.setMidLineWidth(0)
        self.openLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.openLabel.setWordWrap(False)
        self.openLabel.setIndent(4)
        self.openLabel.setObjectName("openLabel")
        self.gridLayout.addWidget(self.openLabel, 7, 0, 1, 1)
        self.closeLabel = QtWidgets.QLabel(self.centralwidget)
        self.closeLabel.setMouseTracking(True)
        self.closeLabel.setStyleSheet("background-color: rgb(78, 154, 6)")
        self.closeLabel.setFrameShape(QtWidgets.QFrame.Panel)
        self.closeLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.closeLabel.setLineWidth(1)
        self.closeLabel.setMidLineWidth(0)
        self.closeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.closeLabel.setWordWrap(False)
        self.closeLabel.setIndent(4)
        self.closeLabel.setObjectName("closeLabel")
        self.gridLayout.addWidget(self.closeLabel, 1, 0, 1, 1)
        self.frontLabel = QtWidgets.QLabel(self.centralwidget)
        self.frontLabel.setMouseTracking(True)
        self.frontLabel.setAutoFillBackground(False)
        self.frontLabel.setStyleSheet("background-color: rgb(78, 154, 6)")
        self.frontLabel.setFrameShape(QtWidgets.QFrame.Panel)
        self.frontLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frontLabel.setLineWidth(1)
        self.frontLabel.setMidLineWidth(0)
        self.frontLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.frontLabel.setWordWrap(False)
        self.frontLabel.setIndent(4)
        self.frontLabel.setObjectName("frontLabel")
        self.gridLayout.addWidget(self.frontLabel, 0, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.close_front_unrounded_vowel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_front_unrounded_vowel.sizePolicy().hasHeightForWidth())
        self.close_front_unrounded_vowel.setSizePolicy(sizePolicy)
        self.close_front_unrounded_vowel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.close_front_unrounded_vowel.setStyleSheet("")
        self.close_front_unrounded_vowel.setObjectName("close_front_unrounded_vowel")
        self.horizontalLayout.addWidget(self.close_front_unrounded_vowel)
        self.close_front_rounded_vowel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_front_rounded_vowel.sizePolicy().hasHeightForWidth())
        self.close_front_rounded_vowel.setSizePolicy(sizePolicy)
        self.close_front_rounded_vowel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.close_front_rounded_vowel.setStyleSheet("")
        self.close_front_rounded_vowel.setAutoDefault(False)
        self.close_front_rounded_vowel.setDefault(False)
        self.close_front_rounded_vowel.setFlat(False)
        self.close_front_rounded_vowel.setObjectName("close_front_rounded_vowel")
        self.horizontalLayout.addWidget(self.close_front_rounded_vowel)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_9.setSpacing(10)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.close_mid_front_rounded_vowel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_mid_front_rounded_vowel.sizePolicy().hasHeightForWidth())
        self.close_mid_front_rounded_vowel.setSizePolicy(sizePolicy)
        self.close_mid_front_rounded_vowel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.close_mid_front_rounded_vowel.setStyleSheet("")
        self.close_mid_front_rounded_vowel.setObjectName("close_mid_front_rounded_vowel")
        self.horizontalLayout_9.addWidget(self.close_mid_front_rounded_vowel)
        self.gridLayout.addLayout(self.horizontalLayout_9, 3, 2, 1, 1)
        self.centralLabel = QtWidgets.QLabel(self.centralwidget)
        self.centralLabel.setMouseTracking(True)
        self.centralLabel.setStyleSheet("background-color: rgb(78, 154, 6)")
        self.centralLabel.setFrameShape(QtWidgets.QFrame.Panel)
        self.centralLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.centralLabel.setLineWidth(1)
        self.centralLabel.setMidLineWidth(0)
        self.centralLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.centralLabel.setWordWrap(False)
        self.centralLabel.setIndent(4)
        self.centralLabel.setObjectName("centralLabel")
        self.gridLayout.addWidget(self.centralLabel, 0, 3, 1, 1)
        self.backLabel = QtWidgets.QLabel(self.centralwidget)
        self.backLabel.setMouseTracking(True)
        self.backLabel.setStyleSheet("background-color: rgb(78, 154, 6)")
        self.backLabel.setFrameShape(QtWidgets.QFrame.Panel)
        self.backLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.backLabel.setLineWidth(1)
        self.backLabel.setMidLineWidth(0)
        self.backLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.backLabel.setWordWrap(False)
        self.backLabel.setIndent(4)
        self.backLabel.setObjectName("backLabel")
        self.gridLayout.addWidget(self.backLabel, 0, 5, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_8.setSpacing(10)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.near_close_near_front_unrounded_vowel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.near_close_near_front_unrounded_vowel.sizePolicy().hasHeightForWidth())
        self.near_close_near_front_unrounded_vowel.setSizePolicy(sizePolicy)
        self.near_close_near_front_unrounded_vowel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.near_close_near_front_unrounded_vowel.setStyleSheet("")
        self.near_close_near_front_unrounded_vowel.setObjectName("near_close_near_front_unrounded_vowel")
        self.horizontalLayout_8.addWidget(self.near_close_near_front_unrounded_vowel)
        self.near_close_near_front_rounded_vowel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.near_close_near_front_rounded_vowel.sizePolicy().hasHeightForWidth())
        self.near_close_near_front_rounded_vowel.setSizePolicy(sizePolicy)
        self.near_close_near_front_rounded_vowel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.near_close_near_front_rounded_vowel.setStyleSheet("")
        self.near_close_near_front_rounded_vowel.setObjectName("near_close_near_front_rounded_vowel")
        self.horizontalLayout_8.addWidget(self.near_close_near_front_rounded_vowel)
        self.gridLayout.addLayout(self.horizontalLayout_8, 2, 2, 1, 1)
        self.openMidLabel = QtWidgets.QLabel(self.centralwidget)
        self.openMidLabel.setMouseTracking(True)
        self.openMidLabel.setStyleSheet("background-color: rgb(78, 154, 6)")
        self.openMidLabel.setFrameShape(QtWidgets.QFrame.Panel)
        self.openMidLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.openMidLabel.setLineWidth(1)
        self.openMidLabel.setMidLineWidth(0)
        self.openMidLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.openMidLabel.setWordWrap(False)
        self.openMidLabel.setIndent(4)
        self.openMidLabel.setObjectName("openMidLabel")
        self.gridLayout.addWidget(self.openMidLabel, 5, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_11.setSpacing(10)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.open_mid_front_unrounded_vowel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_mid_front_unrounded_vowel.sizePolicy().hasHeightForWidth())
        self.open_mid_front_unrounded_vowel.setSizePolicy(sizePolicy)
        self.open_mid_front_unrounded_vowel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.open_mid_front_unrounded_vowel.setStyleSheet("")
        self.open_mid_front_unrounded_vowel.setObjectName("open_mid_front_unrounded_vowel")
        self.horizontalLayout_11.addWidget(self.open_mid_front_unrounded_vowel)
        self.gridLayout.addLayout(self.horizontalLayout_11, 5, 2, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_12.setSpacing(10)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.near_open_front_unrounded_vowel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.near_open_front_unrounded_vowel.sizePolicy().hasHeightForWidth())
        self.near_open_front_unrounded_vowel.setSizePolicy(sizePolicy)
        self.near_open_front_unrounded_vowel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.near_open_front_unrounded_vowel.setStyleSheet("")
        self.near_open_front_unrounded_vowel.setObjectName("near_open_front_unrounded_vowel")
        self.horizontalLayout_12.addWidget(self.near_open_front_unrounded_vowel)
        self.gridLayout.addLayout(self.horizontalLayout_12, 6, 2, 1, 1)
        self.midLabel = QtWidgets.QLabel(self.centralwidget)
        self.midLabel.setMouseTracking(True)
        self.midLabel.setStyleSheet("background-color: rgb(78, 154, 6)")
        self.midLabel.setFrameShape(QtWidgets.QFrame.Panel)
        self.midLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.midLabel.setLineWidth(1)
        self.midLabel.setMidLineWidth(0)
        self.midLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.midLabel.setWordWrap(False)
        self.midLabel.setIndent(4)
        self.midLabel.setObjectName("midLabel")
        self.gridLayout.addWidget(self.midLabel, 4, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.close_mid_front_unrounded_vowel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_mid_front_unrounded_vowel.sizePolicy().hasHeightForWidth())
        self.close_mid_front_unrounded_vowel.setSizePolicy(sizePolicy)
        self.close_mid_front_unrounded_vowel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.close_mid_front_unrounded_vowel.setStyleSheet("")
        self.close_mid_front_unrounded_vowel.setObjectName("close_mid_front_unrounded_vowel")
        self.horizontalLayout_3.addWidget(self.close_mid_front_unrounded_vowel)
        self.gridLayout.addLayout(self.horizontalLayout_3, 3, 1, 1, 1)
        self.nearBackLabel = QtWidgets.QLabel(self.centralwidget)
        self.nearBackLabel.setMouseTracking(True)
        self.nearBackLabel.setStyleSheet("background-color: rgb(78, 154, 6)")
        self.nearBackLabel.setFrameShape(QtWidgets.QFrame.Panel)
        self.nearBackLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.nearBackLabel.setLineWidth(1)
        self.nearBackLabel.setMidLineWidth(0)
        self.nearBackLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nearBackLabel.setWordWrap(False)
        self.nearBackLabel.setIndent(4)
        self.nearBackLabel.setObjectName("nearBackLabel")
        self.gridLayout.addWidget(self.nearBackLabel, 0, 4, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_15.setSpacing(10)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.close_central_unrounded_vowel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_central_unrounded_vowel.sizePolicy().hasHeightForWidth())
        self.close_central_unrounded_vowel.setSizePolicy(sizePolicy)
        self.close_central_unrounded_vowel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.close_central_unrounded_vowel.setStyleSheet("")
        self.close_central_unrounded_vowel.setObjectName("close_central_unrounded_vowel")
        self.horizontalLayout_15.addWidget(self.close_central_unrounded_vowel)
        self.close_central_rounded_vowel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_central_rounded_vowel.sizePolicy().hasHeightForWidth())
        self.close_central_rounded_vowel.setSizePolicy(sizePolicy)
        self.close_central_rounded_vowel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.close_central_rounded_vowel.setStyleSheet("")
        self.close_central_rounded_vowel.setObjectName("close_central_rounded_vowel")
        self.horizontalLayout_15.addWidget(self.close_central_rounded_vowel)
        self.gridLayout.addLayout(self.horizontalLayout_15, 1, 3, 1, 1)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_17.setSpacing(10)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.close_back_unrounded_vowel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_back_unrounded_vowel.sizePolicy().hasHeightForWidth())
        self.close_back_unrounded_vowel.setSizePolicy(sizePolicy)
        self.close_back_unrounded_vowel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.close_back_unrounded_vowel.setStyleSheet("")
        self.close_back_unrounded_vowel.setObjectName("close_back_unrounded_vowel")
        self.horizontalLayout_17.addWidget(self.close_back_unrounded_vowel)
        self.close_back_rounded_vowel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_back_rounded_vowel.sizePolicy().hasHeightForWidth())
        self.close_back_rounded_vowel.setSizePolicy(sizePolicy)
        self.close_back_rounded_vowel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.close_back_rounded_vowel.setStyleSheet("")
        self.close_back_rounded_vowel.setObjectName("close_back_rounded_vowel")
        self.horizontalLayout_17.addWidget(self.close_back_rounded_vowel)
        self.gridLayout.addLayout(self.horizontalLayout_17, 1, 5, 1, 1)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_19.setSpacing(10)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.near_close_near_back_rounded_vowel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.near_close_near_back_rounded_vowel.sizePolicy().hasHeightForWidth())
        self.near_close_near_back_rounded_vowel.setSizePolicy(sizePolicy)
        self.near_close_near_back_rounded_vowel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.near_close_near_back_rounded_vowel.setStyleSheet("")
        self.near_close_near_back_rounded_vowel.setObjectName("near_close_near_back_rounded_vowel")
        self.horizontalLayout_19.addWidget(self.near_close_near_back_rounded_vowel)
        self.gridLayout.addLayout(self.horizontalLayout_19, 2, 4, 1, 1)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_21.setSpacing(10)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.close_mid_central_rounded_vowel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_mid_central_rounded_vowel.sizePolicy().hasHeightForWidth())
        self.close_mid_central_rounded_vowel.setSizePolicy(sizePolicy)
        self.close_mid_central_rounded_vowel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.close_mid_central_rounded_vowel.setStyleSheet("")
        self.close_mid_central_rounded_vowel.setObjectName("close_mid_central_rounded_vowel")
        self.horizontalLayout_21.addWidget(self.close_mid_central_rounded_vowel)
        self.gridLayout.addLayout(self.horizontalLayout_21, 3, 4, 1, 1)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_22.setSpacing(10)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.close_mid_central_unrounded_vowel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_mid_central_unrounded_vowel.sizePolicy().hasHeightForWidth())
        self.close_mid_central_unrounded_vowel.setSizePolicy(sizePolicy)
        self.close_mid_central_unrounded_vowel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.close_mid_central_unrounded_vowel.setStyleSheet("")
        self.close_mid_central_unrounded_vowel.setObjectName("close_mid_central_unrounded_vowel")
        self.horizontalLayout_22.addWidget(self.close_mid_central_unrounded_vowel)
        self.gridLayout.addLayout(self.horizontalLayout_22, 3, 3, 1, 1)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_23.setSpacing(10)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.close_mid_back_unrounded_vowel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_mid_back_unrounded_vowel.sizePolicy().hasHeightForWidth())
        self.close_mid_back_unrounded_vowel.setSizePolicy(sizePolicy)
        self.close_mid_back_unrounded_vowel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.close_mid_back_unrounded_vowel.setStyleSheet("")
        self.close_mid_back_unrounded_vowel.setObjectName("close_mid_back_unrounded_vowel")
        self.horizontalLayout_23.addWidget(self.close_mid_back_unrounded_vowel)
        self.close_mid_back_rounded_vowel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_mid_back_rounded_vowel.sizePolicy().hasHeightForWidth())
        self.close_mid_back_rounded_vowel.setSizePolicy(sizePolicy)
        self.close_mid_back_rounded_vowel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.close_mid_back_rounded_vowel.setStyleSheet("")
        self.close_mid_back_rounded_vowel.setObjectName("close_mid_back_rounded_vowel")
        self.horizontalLayout_23.addWidget(self.close_mid_back_rounded_vowel)
        self.gridLayout.addLayout(self.horizontalLayout_23, 3, 5, 1, 1)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_24.setSpacing(10)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.mid_central_vowel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mid_central_vowel.sizePolicy().hasHeightForWidth())
        self.mid_central_vowel.setSizePolicy(sizePolicy)
        self.mid_central_vowel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.mid_central_vowel.setStyleSheet("")
        self.mid_central_vowel.setObjectName("mid_central_vowel")
        self.horizontalLayout_24.addWidget(self.mid_central_vowel)
        self.gridLayout.addLayout(self.horizontalLayout_24, 4, 3, 1, 1)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_27.setSpacing(10)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.open_mid_front_rounded_vowel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_mid_front_rounded_vowel.sizePolicy().hasHeightForWidth())
        self.open_mid_front_rounded_vowel.setSizePolicy(sizePolicy)
        self.open_mid_front_rounded_vowel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.open_mid_front_rounded_vowel.setStyleSheet("")
        self.open_mid_front_rounded_vowel.setObjectName("open_mid_front_rounded_vowel")
        self.horizontalLayout_27.addWidget(self.open_mid_front_rounded_vowel)
        self.open_mid_central_unrounded_vowel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_mid_central_unrounded_vowel.sizePolicy().hasHeightForWidth())
        self.open_mid_central_unrounded_vowel.setSizePolicy(sizePolicy)
        self.open_mid_central_unrounded_vowel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.open_mid_central_unrounded_vowel.setStyleSheet("")
        self.open_mid_central_unrounded_vowel.setObjectName("open_mid_central_unrounded_vowel")
        self.horizontalLayout_27.addWidget(self.open_mid_central_unrounded_vowel)
        self.gridLayout.addLayout(self.horizontalLayout_27, 5, 3, 1, 1)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_28.setSpacing(10)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.open_mid_central_rounded_vowel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_mid_central_rounded_vowel.sizePolicy().hasHeightForWidth())
        self.open_mid_central_rounded_vowel.setSizePolicy(sizePolicy)
        self.open_mid_central_rounded_vowel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.open_mid_central_rounded_vowel.setStyleSheet("")
        self.open_mid_central_rounded_vowel.setObjectName("open_mid_central_rounded_vowel")
        self.horizontalLayout_28.addWidget(self.open_mid_central_rounded_vowel)
        self.gridLayout.addLayout(self.horizontalLayout_28, 5, 4, 1, 1)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_29.setSpacing(10)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.open_mid_back_unrounded_vowel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_mid_back_unrounded_vowel.sizePolicy().hasHeightForWidth())
        self.open_mid_back_unrounded_vowel.setSizePolicy(sizePolicy)
        self.open_mid_back_unrounded_vowel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.open_mid_back_unrounded_vowel.setStyleSheet("")
        self.open_mid_back_unrounded_vowel.setObjectName("open_mid_back_unrounded_vowel")
        self.horizontalLayout_29.addWidget(self.open_mid_back_unrounded_vowel)
        self.open_mid_back_rounded_vowel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_mid_back_rounded_vowel.sizePolicy().hasHeightForWidth())
        self.open_mid_back_rounded_vowel.setSizePolicy(sizePolicy)
        self.open_mid_back_rounded_vowel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.open_mid_back_rounded_vowel.setStyleSheet("")
        self.open_mid_back_rounded_vowel.setObjectName("open_mid_back_rounded_vowel")
        self.horizontalLayout_29.addWidget(self.open_mid_back_rounded_vowel)
        self.gridLayout.addLayout(self.horizontalLayout_29, 5, 5, 1, 1)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_31.setSpacing(10)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.near_open_central_unrounded_vowel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.near_open_central_unrounded_vowel.sizePolicy().hasHeightForWidth())
        self.near_open_central_unrounded_vowel.setSizePolicy(sizePolicy)
        self.near_open_central_unrounded_vowel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.near_open_central_unrounded_vowel.setStyleSheet("")
        self.near_open_central_unrounded_vowel.setObjectName("near_open_central_unrounded_vowel")
        self.horizontalLayout_31.addWidget(self.near_open_central_unrounded_vowel)
        self.gridLayout.addLayout(self.horizontalLayout_31, 6, 4, 1, 1)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_33.setSpacing(10)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.open_front_unrounded_vowel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_front_unrounded_vowel.sizePolicy().hasHeightForWidth())
        self.open_front_unrounded_vowel.setSizePolicy(sizePolicy)
        self.open_front_unrounded_vowel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.open_front_unrounded_vowel.setStyleSheet("")
        self.open_front_unrounded_vowel.setObjectName("open_front_unrounded_vowel")
        self.horizontalLayout_33.addWidget(self.open_front_unrounded_vowel)
        self.gridLayout.addLayout(self.horizontalLayout_33, 7, 3, 1, 1)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_34.setSpacing(10)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.open_front_rounded_vowel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_front_rounded_vowel.sizePolicy().hasHeightForWidth())
        self.open_front_rounded_vowel.setSizePolicy(sizePolicy)
        self.open_front_rounded_vowel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.open_front_rounded_vowel.setStyleSheet("")
        self.open_front_rounded_vowel.setObjectName("open_front_rounded_vowel")
        self.horizontalLayout_34.addWidget(self.open_front_rounded_vowel)
        self.gridLayout.addLayout(self.horizontalLayout_34, 7, 4, 1, 1)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_35.setSpacing(10)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.open_back_unrounded_vowel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_back_unrounded_vowel.sizePolicy().hasHeightForWidth())
        self.open_back_unrounded_vowel.setSizePolicy(sizePolicy)
        self.open_back_unrounded_vowel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.open_back_unrounded_vowel.setStyleSheet("")
        self.open_back_unrounded_vowel.setObjectName("open_back_unrounded_vowel")
        self.horizontalLayout_35.addWidget(self.open_back_unrounded_vowel)
        self.open_back_rounded_vowel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_back_rounded_vowel.sizePolicy().hasHeightForWidth())
        self.open_back_rounded_vowel.setSizePolicy(sizePolicy)
        self.open_back_rounded_vowel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.open_back_rounded_vowel.setStyleSheet("")
        self.open_back_rounded_vowel.setObjectName("open_back_rounded_vowel")
        self.horizontalLayout_35.addWidget(self.open_back_rounded_vowel)
        self.gridLayout.addLayout(self.horizontalLayout_35, 7, 5, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 5, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 4, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 6, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 2, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 4, 2, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 2, 3, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 6, 5, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "IPA"))
        self.vowelsLabel.setText(_translate("MainWindow", "VOWELS"))
        self.nearCloseLabel.setText(_translate("MainWindow", "  NEAR-CLOSE  "))
        self.nearFrontLabel.setText(_translate("MainWindow", "NEAR-FRONT"))
        self.closeMidLabel.setText(_translate("MainWindow", "CLOSE-MID"))
        self.nearOpenLabel.setText(_translate("MainWindow", "NEAR-OPEN"))
        self.openLabel.setText(_translate("MainWindow", "OPEN"))
        self.closeLabel.setText(_translate("MainWindow", "CLOSE"))
        self.frontLabel.setText(_translate("MainWindow", "FRONT"))
        self.close_front_unrounded_vowel.setText(_translate("MainWindow", "i"))
        self.close_front_rounded_vowel.setText(_translate("MainWindow", "y"))
        self.close_mid_front_rounded_vowel.setText(_translate("MainWindow", "ø"))
        self.centralLabel.setText(_translate("MainWindow", "CENTRAL"))
        self.backLabel.setText(_translate("MainWindow", "BACK"))
        self.near_close_near_front_unrounded_vowel.setText(_translate("MainWindow", "ɪ"))
        self.near_close_near_front_rounded_vowel.setText(_translate("MainWindow", "ʏ"))
        self.openMidLabel.setText(_translate("MainWindow", "OPEN-MID"))
        self.open_mid_front_unrounded_vowel.setText(_translate("MainWindow", "ɛ"))
        self.near_open_front_unrounded_vowel.setText(_translate("MainWindow", "æ"))
        self.midLabel.setText(_translate("MainWindow", "MID"))
        self.close_mid_front_unrounded_vowel.setText(_translate("MainWindow", "e"))
        self.nearBackLabel.setText(_translate("MainWindow", "NEAR-BACK"))
        self.close_central_unrounded_vowel.setText(_translate("MainWindow", "ɨ"))
        self.close_central_rounded_vowel.setText(_translate("MainWindow", "ʉ"))
        self.close_back_unrounded_vowel.setText(_translate("MainWindow", "ɯ"))
        self.close_back_rounded_vowel.setText(_translate("MainWindow", "u"))
        self.near_close_near_back_rounded_vowel.setText(_translate("MainWindow", "ʊ"))
        self.close_mid_central_rounded_vowel.setText(_translate("MainWindow", "ɵ"))
        self.close_mid_central_unrounded_vowel.setText(_translate("MainWindow", "ɘ"))
        self.close_mid_back_unrounded_vowel.setText(_translate("MainWindow", "ɤ"))
        self.close_mid_back_rounded_vowel.setText(_translate("MainWindow", "o"))
        self.mid_central_vowel.setText(_translate("MainWindow", "ə"))
        self.open_mid_front_rounded_vowel.setText(_translate("MainWindow", "œ"))
        self.open_mid_central_unrounded_vowel.setText(_translate("MainWindow", "ɜ"))
        self.open_mid_central_rounded_vowel.setText(_translate("MainWindow", "ɞ"))
        self.open_mid_back_unrounded_vowel.setText(_translate("MainWindow", "ʌ"))
        self.open_mid_back_rounded_vowel.setText(_translate("MainWindow", "ɔ"))
        self.near_open_central_unrounded_vowel.setText(_translate("MainWindow", "ɐ"))
        self.open_front_unrounded_vowel.setText(_translate("MainWindow", "a"))
        self.open_front_rounded_vowel.setText(_translate("MainWindow", "ä"))
        self.open_back_unrounded_vowel.setText(_translate("MainWindow", "ɑ"))
        self.open_back_rounded_vowel.setText(_translate("MainWindow", "ɒ"))

